### ISSUE TITLE
Error in sharing dialog on iOS 14

### ISSUE THREAD

**Issue by Lavelak** [natsuite/NatShare-API#101]
iOS version: iOS 14.0.1
NatShare version: 1.2.3

When share() function is called, iOS has this nice looking zoom-out effect with black border around the app, then the share screen appears, and right after sharing the content the app freezes.

> 2020-10-26 11:04:13.707052+0200 qa[1822:504297] [LayoutConstraints] Unable to simultaneously satisfy constraints.
    Probably at least one of the constraints in the following list is one you don't want. 
    Try this: 
        (1) look at each constraint and try to figure out which you don't expect; 
        (2) find the code that added the unwanted constraint or constraints and fix it. 
(
  "<NSLayoutConstraint:0x281443ca0 _UIActivityActionCellTitleLabel:0x125bb9180.height >= 22  (active)>",
  "<NSLayoutConstraint:0x2814437f0 V:|-(15)-[_UIActivityActionCellTitleLabel:0x125bb9180]  (active, names: '|':UIView:0x12b5db390 )>",
  "<NSLayoutConstraint:0x281443840 V:[_UIActivityActionCellTitleLabel:0x125bb9180]-(15)-|  (active, names: '|':UIView:0x12b5db390 )>",
  "<NSLayoutConstraint:0x281455ea0 'UIView-Encapsulated-Layout-Height' UIView:0x12b5db390.height == 50.3333  (active)>"
)

**Comment by Lavelak** [comment]
Ok,
so the app is not crashing. It freezes until the content is shared and then unfreezes.
Shouldn't the upload happen in background? At least  that's what happens on Android.
And also, it feel like its taking forever (like 15-20sec) to upload and there's no progress indicator.

**Comment by olokobayusuf** [comment]
I'll see if I can reproduce this. I don't know what you mean by "upload". What upload? Where are you uploading to?

**Comment by Lavelak** [comment]
Yeah, what I meant was that NatShare freezes while the content is being shared. The Unity app itself is running fine in the background, but the user can't interact with it, because the share popup is blocking the view.

**Comment by olokobayusuf** [comment]
> Yeah, what I meant was that NatShare freezes while the content is being shared. The Unity app itself is running fine in the background, but the user can't interact with it, because the share popup is blocking the view.

Make sure to always be descriptive when you report issues; it saves everybody time. I'll look into this.

**Comment by olokobayusuf** [comment]
@Lavelak I can't reproduce the freeze. I see the UI constraint error come up, but I think that's because of Unity, and it is innocuous as far as I can tell. Sharing works as normal.
