### ISSUE TITLE
App freezes when saving

### ISSUE THREAD

**Issue by aholla** [natsuite/NatShare-API#102]
I am using the save functionality to save a video on iOS.

When I first call the script I get a permissions popup with 3 options.

- Select Photos...
- Allow Access to All Photos
- Don't Allow

If I choose the first option "Select Photos" the app freezes. There are no logs, it just locks up.

If I close the app and relaunch it and try again, it works. the first video during the freeze is not saved either.

Using iphone 7, IOS 14. Unity 2020.1

**Comment by olokobayusuf** [comment]
This has been fixed in #97
