### ISSUE TITLE
NSPhotoLibraryUsageDescription required on iOS 14?

### ISSUE THREAD

**Issue by sam598** [natsuite/NatShare-API#103]
If all `SavePayload` is doing is writing to disk, it should only need `NSPhotoLibraryAddUsageDescription` and not `NSPhotoLibraryUsageDescription`.

In iOS 14 `NSPhotoLibraryUsageDescription` asks the user if and how the user wants the app to access their camera roll. This notification is undesirable and may lead to app store rejection.

**Comment by olokobayusuf** [comment]
You raise a really good point. The only issue is that on older versions of iOS, the `NSPhotoLibraryAddUsageDescription` was not enough; you also had to specify the `NSPhotoLibraryUsageDescription` else you'd get a hard crash. So the common denominator here would be to simply specify `NSPhotoLibraryUsageDescription` and only that. As for the notification, you can disable it. [See this article](https://developer.apple.com/documentation/photokit/delivering_a_great_privacy_experience_in_your_photos_app?language=objc).
