### ISSUE TITLE
payload API AddMedia() with image path not work

### ISSUE THREAD

**Issue by pofulu** [natsuite/NatShare-API#60]
I tried to AddMeida() with image path, but the image wasn't be saved in to CameraRoll. 
AddImage() with Texture2D works fine.
Tested on Android and iOS both.

**Comment by olokobayusuf** [comment]
On iOS, `SavePayload::AddMedia` expects a video file. I'll look into generalizing this. What Android version are you running on?

**Comment by pofulu** [comment]
I tested on Android 9 (9 PKQ 1.180729.001).

**Comment by olokobayusuf** [comment]
iOS fixed in 960051ca5cb0fd524dbb49c9af371eddb9fc255a

**Comment by olokobayusuf** [comment]
Can you share the logs for this
