### ISSUE TITLE
Crash when sharing iOS, missing NSPhotoLibraryAddUsageDescription

### ISSUE THREAD

**Issue by luizjunior** [natsuite/NatShare-API#62]
Hi, please update PostProcessBuild to include NSPhotoLibraryAddUsageDescription

iOS (13.1.3) crashes when trying to Save Image.

[access] This app has crashed because it attempted to access privacy-sensitive data without a usage description.  The app's Info.plist must contain an NSPhotoLibraryAddUsageDescription key with a string value explaining to the user how the app uses this data.

**Comment by luizjunior** [comment]
Yes but should add also:  NSPhotoLibraryAddUsageDescription
NSPhotoLibrary**Add**UsageDescription
NSPhotoLibraryUsageDescription

they are slightly different.

**Comment by olokobayusuf** [comment]
That's what I'm saying. See my post above.

**Comment by luizjunior** [comment]
Yes, it's strange but if we check the documentation it says:
NSPhotoLibraryAddUsageDescription: If you want to save a photo/image to your Photo Library. For iOS11 and +

NSPhotoLibraryUsageDescription: If you want to access your Photo Library. For iOS10 and +

[https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html#//apple_ref/doc/uid/TP40009251-SW73](url)

It seems that since iOS 11, NSPhotoLibraryAddUsageDescription is used to WRITE and NSPhotoLibraryUsageDescription to access (I believe they mean access = READ).

Anyway, it's crashing on iOS (13.1.3).

I've added NSPhotoLibraryAddUsageDescription to my last build and it's ok now.

keep with the good work

**Comment by olokobayusuf** [comment]
c2d6ae48e81cb817e20626ef4e0f9f6b4b0ab54a
