### ISSUE TITLE
Crash on Android after Sharing video

### ISSUE THREAD

**Issue by KevinLDAS** [natsuite/NatShare-API#64]
Hello, I recorded video with NatCorder, then tried to share it using the NatShare function.
I believe the crash was caused by an error in the share callback function I wrote.
I was completely lost on the cause of the error, as it wasn't happening before. I exported the project into Android Studio, and tried to debug it from there. By luck, when going over the error logs, I found that it threw an error during the Share callback where I tried to use `preview.gameObject.SetActive(false);` in my callback function. Evidently the callback doesn't run in the main Unity thread, and therefore you can't make references like these. Maybe I should've expected that, but it didn't occur to me. To work around it, I just am setting a boolean in the callback, and then in Update (which is always in the main Unity thread) I am doing the .gameObject call, then resetting the boolean.
I forgot to grab the logs, but I am pretty sure this is what caused my issue, as I've run into thread bugs before on other projects, and they seem to behave about the same way, giving very little warning.

You can close this, but it was a cause of confusion for me. So I thought you should be made aware, and I think including information about absolutely never doing main-thread-only things in the callback function should definitely considered.

**Comment by olokobayusuf** [comment]
I usually always check that callbacks are invoked on the Unity main thread. I'll definitely make sure to keep you in the loop as the Android backend for #49 is complete. Thanks for the investigations.
