### ISSUE TITLE
Image sharing content issue

### ISSUE THREAD

**Issue by marad747** [natsuite/NatShare-API#65]
in my app i made screenshot and load to preview 
![image](https://user-images.githubusercontent.com/20600166/68038178-0ba1de00-fcd2-11e9-9d66-153fbd6ed79a.png)
when i want to share my image are RED
![image](https://user-images.githubusercontent.com/20600166/68038249-2c6a3380-fcd2-11e9-9a2f-b500ecba021a.png)
ios 13.1.13, use #49 version plugin

**Comment by olokobayusuf** [comment]
Your image must have an `RGBA32` format.
