### ISSUE TITLE
ios 13 crash

### ISSUE THREAD

**Issue by ghus86** [natsuite/NatShare-API#67]
Hi @olokobayusuf 

First your apis are very useful, I have nat cam and nat corder thanks for that=)

But I am having an issue with the latest version of natshare in unity 2019.2 
and the latest version iOS 13.2.2
when I use the save to camera roll everything is fine
but I get a crash if I use share option 

[Animation] +[UIView setAnimationsEnabled:] being called from a background thread. Performing any operation from a background thread on UIView or a subclass is not supported and may result in unexpected and insidious behavior.

Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Modifications to the layout engine must not be performed from a background thread after it has been accessed from the main thread.'

Due you have an ideia of what is happening ?

**Comment by olokobayusuf** [comment]
This is fixed in #49. The iOS backend is complete, so you can pull the code into your project.
