### ISSUE TITLE
Implement setting position of share dialogue on iPad devices

### ISSUE THREAD

**Issue by nicholasmaurer** [natsuite/NatShare-API#68]
Currently the share dialogue opens in the top right. It would be good if we could set the position of the share dialogue.

![ipad-share-dialogue-natshare](https://user-images.githubusercontent.com/22599013/70096644-a7c95700-167b-11ea-9783-04906b9f0606.jpeg)

**Comment by olokobayusuf** [comment]
This is specific to iPad only, so it won't be ideal to implement. The challenge with cross-platform API's is being constrained to functionality that is common to all platforms. For something like this I recommend cloning and modding NatShare so your app can use this functionality.

**Comment by olokobayusuf** [comment]
Perhaps a compromise would be to make the share sheet always appear on the bottom on iPad, so it remains consistent with iPhone and Android. But it would **not** be configurable from the client API. Thoughts?

**Comment by nicholasmaurer** [comment]
Yeah I think that's a good compromise.
