### ISSUE TITLE
Permission issue when saving to camera roll on iOS

### ISSUE THREAD

**Issue by Dryra** [natsuite/NatShare-API#69]
Hello, 
Using the payload-api version for iOS, on first install when the saving to library permission is not granted yet, on saving an image or a video to the camera roll, the app asks for library permission,and when allowed, the image or video does not get saved, but return a success callback and not error logs, only the next time when you click on save again and the permission is already granted.
Thank you.

Unity Version: 2019.1.6f1
iOS Version: 13.2.3
iPhone 11

**Comment by olokobayusuf** [comment]
Fixed in 1578ec99f066ea552554df3d9108339cfe80f2e5
