### ISSUE TITLE
More diligence on sharing payload MIME types

### ISSUE THREAD

**Issue by olokobayusuf** [natsuite/NatShare-API#74]

**Comment by ShengShangShung** [comment]
Hi there, 

New on this Natshare features, currently having some issues with iOS and Android when sharing to Instagram.

iOS side: Managed to open the share page, but the keyboard won't appear and the "post" button won't able to press on it.

Android side: When click on "Feed" button on ShareSheet, it just open the Instagram without my post.

Here are my code snippet as an image.

![image](https://user-images.githubusercontent.com/59740462/72168090-6d37a480-3407-11ea-9904-4f866536cf09.png)

**Comment by olokobayusuf** [comment]
The iOS issue sounds outside of NatShare's control. This issue focuses on setting the proper MIME type of the share payload, in case Instagram uses it to determine what to do with the shared media.

**Comment by ShengShangShung** [comment]
Then what about Android side? Is there anything I missed?

**Comment by ShengShangShung** [comment]
Now I'm updated the iOS to 13.3 and now after taking a picture or video, the share sheet does not shows up.

**Comment by olokobayusuf** [comment]
> Now I'm updated the iOS to 13.3 and now after taking a picture or video, the share sheet does not shows up.
> 
> `2020-01-11 15:43:44.377197+0800 cny[1608:23576] [LayoutConstraints] Unable to simultaneously satisfy constraints.
> Probably at least one of the constraints in the following list is one you don't want.
> Try this:
> (1) look at each constraint and try to figure out which you don't expect;
> (2) find the code that added the unwanted constraint or constraints and fix it.
> (
> "<NSLayoutConstraint:0x282ed9630 LPLinkView:0x129789870.leading == UILayoutGuide:0x2836e72c0'UIViewLayoutMarginsGuide'.leading (active)>",
> "<NSLayoutConstraint:0x282ed9270 H:[LPLinkView:0x129789870]-(59)-| (active, names: '|':_UIActivityContentTitleView:0x129791b70 )>",
> "<NSLayoutConstraint:0x282ede800 H:|-(0)-[_UIActivityContentTitleView:0x129791b70] (active, names: '|':_UINavigationBarContentView:0x12ae82890 )>",
> "<NSLayoutConstraint:0x282ede7b0 _UIActivityContentTitleView:0x129791b70.trailing == _UINavigationBarContentView:0x12ae82890.trailing (active)>",
> "<NSLayoutConstraint:0x282ea8910 'UIView-Encapsulated-Layout-Width' _UINavigationBarContentView:0x12ae82890.width == 6 (active)>",
> "<NSLayoutConstraint:0x282ed9540 'UIView-leftMargin-guide-constraint' H:|-(16)-[UILayoutGuide:0x2836e72c0'UIViewLayoutMarginsGuide'](LTR) (active, names: '|':_UIActivityContentTitleView:0x129791b70 )>"
> )
> 
> Will attempt to recover by breaking constraint
> <NSLayoutConstraint:0x282ed9630 LPLinkView:0x129789870.leading == UILayoutGuide:0x2836e72c0'UIViewLayoutMarginsGuide'.leading (active)>`
> 
> And this is what it shows on XCode.

I'll look into this.
