### ISSUE TITLE
Fail when building on Android

### ISSUE THREAD

**Issue by kickassQc** [natsuite/NatShare-API#87]
I tried to make a build on Android and it's failing every time. 

Unity : 2019.3.9f1

![download (1)](https://user-images.githubusercontent.com/12952467/79520778-8fa01600-8025-11ea-978a-434de85ee172.png)

**Comment by olokobayusuf** [comment]
It's more helpful to copy the text in the error and paste it here than to use a screenshot which truncates the actual error. Without seeing the full error log I don't know exactly what is going on. If you're facing build issues with `il2cpp`, then it is likely the issue fixed in #84
