### ISSUE TITLE
Missing symbols on ARMv64

### ISSUE THREAD

**Issue by zkybeijing** [natsuite/NatShare-API#89]
![image](https://user-images.githubusercontent.com/42861621/81376159-893d1f80-9135-11ea-9f3f-5d6ab49c63b6.png)
![image](https://user-images.githubusercontent.com/42861621/81376193-9bb75900-9135-11ea-8946-8c411814a081.png)
![image](https://user-images.githubusercontent.com/42861621/81376226-aa057500-9135-11ea-8011-38dd4d5ebbee.png)
ld: warning: arm64 function not 4-byte aligned: _unwind_tester from /Users/adminuser/Documents/lobby/Solitaire-Unity/Export/iOSBuild/Libraries/libiPhone-lib.a(unwind_test_arm64.o)
Undefined symbols for architecture arm64:
  "_NCEncodeSamples", referenced from:
      _MediaRecorderBridge_EncodeSamples_mB7B02B4BEE53CF514F7C66B4E0CF659A572E01C0 in Assembly-CSharp18.o
      _MediaRecorderiOS_CommitSamples_mAAC4711641ED1E0795BAB028E2363C6A4DC50B9C in Assembly-CSharp18.o
  "_NCEncodeFrame", referenced from:
      _MediaRecorderBridge_EncodeFrame_m11B197C0DB5AE78EAA9083FAA07DAD343698246D in Assembly-CSharp18.o
      _MediaRecorderiOS_CommitFrame_m75B4141A18D5A05DF3F18C974252AF91C69947B2 in Assembly-CSharp18.o
  "_NCStopRecording", referenced from:
      _MediaRecorderBridge_StopRecording_mA4CFDBBD6CDFE7576B30729CC56B7B2A211E9C98 in Assembly-CSharp18.o
      _MediaRecorderiOS_Dispose_m73BCCDE24383DF120D7252C9E369FDEDE416D46F in Assembly-CSharp18.o
  "_NCStartRecording", referenced from:
      _MediaRecorderBridge_StartRecording_m1647875A066BCDC5F09CB79D1E2BA01F3197E32D in Assembly-CSharp18.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

There is no problem with the mobile phone test. There is an error when archiving

**Comment by olokobayusuf** [comment]
Please post NatCorder issues on the [Unity forum thread](https://forum.unity.com/threads/natcorder-video-recording-api.505146/). This repository is for NatShare.

For the above errors, delete NatCorder in your project (delete the `NatSuite` and/or `NatCorder` folders) then reimport from the Asset Store. Then delete your Xcode project and rebuild from Unity.
