### ISSUE TITLE
No apps can perfom this action

### ISSUE THREAD

**Issue by tamizhuser** [natsuite/NatShare-API#91]
I am share the Text content  using nat share. Once I call the share function of Text mobile (Android ) was pop for the "No apps can perfom this action.
Using code is below,

 public void ShareApp()
        {
            switch (Application.platform)
            {
                case RuntimePlatform.IPhonePlayer:                   
                    new SharePayload().AddText("APPSTORE_LINK").Commit();
                    break;
        			
                case RuntimePlatform.Android:
                    new SharePayload().AddText("PLAYSTORE_SHARE_LINK").Commit();
                    break;
            }
        }

Please Help me.,

Regards Tamizhan

**Comment by olokobayusuf** [comment]
Thanks for reporting this issue. I'll look into it and get back to you.

**Comment by tamizhuser** [comment]
Thanks a Lot

**Comment by tamizhuser** [comment]
Hai developer.
Any update on this?

**Comment by olokobayusuf** [comment]
Not yet, I haven't been able to test this out. I will try to do so this weekend. Sorry for the delay.

**Comment by tamizhuser** [comment]
Please if you correct it then inform me .

**Comment by olokobayusuf** [comment]
This issue has been fixed in #93, 70efce4911221e8dfcd013cf4c6b4d63d01d2843
