### ISSUE TITLE
Commit() method

### ISSUE THREAD

**Issue by vahabahmadvand** [natsuite/NatShare-API#92]
there isn't any Commit method in SavePayload, what is an alternative method for that? in pseudo code in readme file used it but no longer exist

**Comment by olokobayusuf** [comment]
I'm not sure what you mean: https://github.com/natsuite/NatShare-API/blob/2388db6d87806d57cad59ff1e558a3335b6c9593/Assets/NatShare/Plugins/Managed/SavePayload.cs#L62-L66

**Comment by vahabahmadvand** [comment]
I downloaded Unitypackage version 1.2 and there wasn't The Commit method

**Comment by olokobayusuf** [comment]
Are you using [1.2.2](https://github.com/natsuite/NatShare-API/releases/tag/1.2-builds)?

**Comment by vahabahmadvand** [comment]
No. I used 1.2.0 and now my problem solved by clone repository
